Repository drewlearns/OS_100days, pull requests merged in 2022-10, with the labels that each got.

#10 fix calendar typo
  index.html
Labels: coding with drew, hacktoberfest

#12 Changed file name from contributors to contributing
  CONTRIBUTING.md
Labels: bug, coding with drew, hacktoberfest

#13 Bring main to date
  CONTRIBUTING.md
  FAQs.html
  about.html
  index.html
Labels: coding with drew, hacktoberfest, hacktoberfest-accepted

#9 Minor Updates
  FAQs.html
  about.html
  index.html
Labels: coding with drew, planning, hacktoberfest

#18 added forms
  signin.html
  signup.html
Labels: good first issue, coding with drew, planning, hacktoberfest

#21 Added logo ideas
  images/100DOC1.png
  images/100DOC2.png
  images/100DOC3.png
  images/100DOC4.png
Labels: coding with drew, hacktoberfest

#26 Fixed typos in index.html
  index.html
Labels: coding with drew, hacktoberfest

#30 added signup.ejs file
  OS_100days/routes/index.js
  OS_100days/views/signup.ejs
Labels: coding with drew, hacktoberfest, hacktoberfest-accepted

#34 modify instructions and fix bug
  README.md
  views/partials/navbar.ejs
Labels: bug, documentation, coding with drew, hacktoberfest, hacktoberfest-accepted
